spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    url: jdbc:mysql://172.30.34.66:3306/community_v2
    username: root
    password: TLMTEAMYLL4523..

server:
  port: 8008

# 选择api项目下的resouces路径下的user文件夹
# filePath: "/Users/yangyida/Documents/project/complaint_system/web-server/src/main/resources/img/user/"
filePath: "D:/Desktop/demo/Community-system/core/src/main/resources/img/user/"
# 服务器url路径
projecturl: "http://127.0.0.1:8008"


